server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 289929730693-kl9cp9lv08ndkga288mtoqp28n19ash9.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          naver:
            client-id: bFhf4UlESniYY2XBMsdw
            client-secret: zzQdIbbuD6
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver #spring에서 기본적으로 제공되는 provider가 아니기 때문에 풀 uri 주소를 기입 해주서야 한다
      provider:
         naver:
           authorization-uri: https://nid.naver.com/oauth2.0/authorize
           token-uri: https://nid.naver.com/oauth2.0/token
           user-info-uri: https://openapi.naver.com/v1/nid/me
           user-name-attribute: response #회원 정보를 json으로 받는데 response 라는 키 값으로 네이버가 리턴해줌



  ##확장자를 머스테치로 바로 인식 가능하게 함
  #  mvc:
  #    view:
  #      prefix: /templates/
  #      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true